version: "3.1"

volumes:
  kpd_data:
  
services:
  db:
    image: postgres
    ports:
      - "5432:5432"
    restart: unless-stopped
    env_file: ./backend/.env
    volumes: 
      - kpd_data:/var/lib/postgresql/data

  backend:
    image: "elanatollu/kpd-api:1"
    build: ./backend
    ports: 
      - "4000:3000"
    restart: unless-stopped
    depends_on:
      - "db"
    links:
      - "db"
    env_file: ./backend/.env

  frontend:
    image: "elanatollu/kpd-frontend:1"
    build: ./frontend
    ports: 
      - "8081:80"
    restart: unless-stopped
    depends_on:
      - "backend"

    
    