version: "3.1"

volumes:
  kpd_data:
  
services:
  db:
    image: postgres
    ports:
      - "5432:5432"
    restart: always
    environment:
      POSTGRES_DB: kpd
      POSTGRES_USER: kpd_user
      POSTGRES_PASSWORD: kpd_password
      PGDATA: /var/lib/postgresql/data/pgdata
    volumes: 
      - kpd_data:/var/lib/postgresql/data

  backend:
    image: "elanatollu/kpd-api:1"
    build: .
    ports: 
      - "4000:3000"
    restart: unless-stopped
    depends_on:
      - "db"
    links:
      - "db"
    env_file: .env

    
    